# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Configamajig < Formula
  desc ""
  homepage "https://github.com/mtintes/homebrew-configamajig"
  version "0.0.22"

  on_macos do
    on_intel do
      url "https://github.com/mtintes/configamajig/releases/download/v0.0.22/configamajig_Darwin_x86_64.tar.gz"
      sha256 "3351041990d2d8360a78077b318f42042ff97bbef270c814c5c2d523d2a848d4"

      def install
        bin.install "configamajig"
      end
    end
    on_arm do
      url "https://github.com/mtintes/configamajig/releases/download/v0.0.22/configamajig_Darwin_arm64.tar.gz"
      sha256 "19e56d52419bed0eb2a0563f60bc663e40f7794c9aebc79bfb8a42f092380808"

      def install
        bin.install "configamajig"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mtintes/configamajig/releases/download/v0.0.22/configamajig_Linux_x86_64.tar.gz"
        sha256 "45cf1900749f62b0b4943ad92952cd09e524c90f01f4b5ca32f45202c1fa16ce"

        def install
          bin.install "configamajig"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mtintes/configamajig/releases/download/v0.0.22/configamajig_Linux_arm64.tar.gz"
        sha256 "144626cc2018d41ba7c6753614b33bf20191833ac381edfd34b38476ee3167d6"

        def install
          bin.install "configamajig"
        end
      end
    end
  end
end
