# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Configamajig < Formula
  desc ""
  homepage "https://github.com/mtintes/homebrew-configamajig"
  version "0.0.21"

  on_macos do
    on_intel do
      url "https://github.com/mtintes/configamajig/releases/download/v0.0.21/configamajig_Darwin_x86_64.tar.gz"
      sha256 "b528c68e8038789ea1a8c52c9cfd20cceded2f5c0b99525df507f01562fc684e"

      def install
        bin.install "configamajig"
      end
    end
    on_arm do
      url "https://github.com/mtintes/configamajig/releases/download/v0.0.21/configamajig_Darwin_arm64.tar.gz"
      sha256 "279d8363cdf71cf8dfe3e37dd6f65edf2e1f55c2f4dacd5836f704a22035984d"

      def install
        bin.install "configamajig"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mtintes/configamajig/releases/download/v0.0.21/configamajig_Linux_x86_64.tar.gz"
        sha256 "5abff7d3153134596ae516db22e73ec5615cf1d3fd0879f65e1a53cbe9a6b72b"

        def install
          bin.install "configamajig"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mtintes/configamajig/releases/download/v0.0.21/configamajig_Linux_arm64.tar.gz"
        sha256 "be2057d4f8f9e32f6c6835a1e5323bedf8bace4995502daf18c05c03f8dd9522"

        def install
          bin.install "configamajig"
        end
      end
    end
  end
end
