# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Configamjig < Formula
  desc ""
  homepage "https://github.com/mtintes/homebrew-configamajig"
  version "0.0.20"

  on_macos do
    on_intel do
      url "https://github.com/mtintes/configamajig/releases/download/v0.0.20/configamajig_Darwin_x86_64.tar.gz"
      sha256 "9d6ab762548dcbe8daf4f448040de2cac40b57e153c4d9a5ef053be74beca277"

      def install
        bin.install "configamajig"
      end
    end
    on_arm do
      url "https://github.com/mtintes/configamajig/releases/download/v0.0.20/configamajig_Darwin_arm64.tar.gz"
      sha256 "77e1949405919968ff0b839447da2d1f2b5e05759cf679e0503b3afe372abd4f"

      def install
        bin.install "configamajig"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mtintes/configamajig/releases/download/v0.0.20/configamajig_Linux_x86_64.tar.gz"
        sha256 "fa2ebaf248fa6ee2d5e58059e2862b3611e11e75fe767deff2b1d67b3381b9bb"

        def install
          bin.install "configamajig"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mtintes/configamajig/releases/download/v0.0.20/configamajig_Linux_arm64.tar.gz"
        sha256 "3ad7be300eb9822891e31029bacdb3d30393e54ebe988ad6c713d8fb7f3722c7"

        def install
          bin.install "configamajig"
        end
      end
    end
  end
end
